### ISSUE TITLE
Minor bug for one-dimensional problems

### ISSUE THREAD

**Issue by parsiad** [maziarraissi/FBSNNs#1]
As a sanity check, I was trying the network for a one-dimensional problem and noticed you need to add `axis=[-1]` as an argument to `tf.squeeze` on line 105 of FBSNN.py. Otherwise, TF squeezes axes 0 and 1 (instead of just axis 2). Here is the updated line:

`X1 = X0 + self.mu_tf(t0,X0,Y0,Z0)*(t1-t0) + tf.squeeze(tf.matmul(self.sigma_tf(t0,X0,Y0),tf.expand_dims(W1-W0,-1)), axis=[-1])`

**Comment by maziarraissi** [comment]
Thanks Parsiad!
